#### 1.   Describe the features of numpy.

##### Numpy:
    is the fundamental package of numerical computing in python.it porovides support for arrays and mtrices along with the mathematical functions to perform operations on arrays.

-     N Dimensional Array :- Numpy main object is homogenious muiltidimensional array called "ndarray".These arrays can have any number of dimensions and contain                       elements of same data type.
-     Effective operations :- Numpy provides wide range of mathematical functions that operate element wise in an array enabling efficient numerical computation
-     Broadcastinng :- Numpy  Broadcasting allows operations between array of different shapes and sizes without explicitly iterate over them which can simplify code and performance.
-     Indexing and slicing :- Numpy offers a poerful indexing and slicing to accessing and modifing of array elements including advanced techniques boolean indexing and fancy indexing
-     Integration with the other libraries :- Numpy is the foundation of other scientific libraries of python such as scipy,Mathplotlib,scikit-learn it integrate with these libraries.
  

 #### 2. Write the applications of numpy.

1.Mathematical and Statistical Operations:

-      NumPy provides a vast range of mathematical functions, including basic arithmetic operations, statistical functions, and more complex mathematical computations.
        
-        Example: Calculating the mean, median, standard deviation, and correlation coefficients.

2.Data Analysis:

-    NumPy is used extensively in data analysis and manipulation, often as a foundational tool for other libraries like pandas.
    
-    Example: Efficiently handling and processing large datasets, cleaning data, and performing exploratory data analysis.

3.Machine Learning:

-    NumPy is a core component in many machine learning frameworks, providing support for matrix operations and linear algebra.
    
-    Example: Implementing algorithms like linear regression, neural networks, and other machine learning models.

4.Scientific Computing:

-    NumPy is essential for scientific computing, providing tools for numerical simulations, solving differential equations, and more.
    
-    Example: Simulating physical phenomena, modeling complex systems, and performing numerical experiments.
5.Image Processing:

-    NumPy is used in image processing tasks, enabling the manipulation and analysis of image data.
    
-    Example: Reading, transforming, and analyzing images, applying filters, and performing image segmentation.

6.Financial Analysis:

-    NumPy is widely used in financial analysis for tasks like calculating returns, risk metrics, and portfolio optimization.
    
-    Example: Analyzing stock prices, computing financial ratios, and optimizing investment portfolios.

7.Signal Processing:

-    NumPy supports signal processing tasks, including filtering, Fourier transforms, and convolution operations.
    
-    Example: Processing audio signals, analyzing time series data, and performing spectral analysis.

8.Data Visualization:

-    NumPy works seamlessly with data visualization libraries like Matplotlib to create visual representations of data.
    
-    Example: Plotting graphs, creating charts, and visualizing complex datasets.

9.Linear Algebra:

-    NumPy provides extensive support for linear algebra operations, including matrix multiplication, eigenvalue computation, and solving linear equations.
    
-    Example: Performing matrix factorizations, solving systems of linear equations, and working with eigenvectors and eigenvalues.

10.Interfacing with Other Languages:

-    NumPy can interface with other programming languages like C, C++, and Fortran, enabling high-performance computing.
    
-    Example: Integrating C/C++ code for performance-critical sections, using Fortran libraries, and extending Python with compiled code.



#### 3.How numpy is different from python sequences.

        Numpy arrays and python lists are both used to store the collection data.but they are diffrent in terms of functionalities,data usage,performance
        Here are differences:

Here are some key differences between NumPy arrays and Python lists:

1.Performance:

-    NumPy Arrays: Optimized for numerical operations and can perform computations much faster than Python lists.
    
-    Python Lists: General-purpose containers that can hold different types of objects. Not optimized for numerical operations.

2.Homogeneity:

-    NumPy Arrays: Elements must be of the same data type.
    
-    Python Lists: Can contain elements of different data types (e.g., integers, strings, and floats).

3.Memory Efficiency:

-    NumPy Arrays: Use less memory to store data compared to Python lists.
    
-    Python Lists: Use more memory due to the overhead of storing type information and pointers for each element.

4.Functionalities:

-    NumPy Arrays: Provide a vast range of built-in mathematical functions and broadcasting capabilities.
    
-    Python Lists: Have fewer built-in functions for numerical operations.

5.Mutability:

-   Both: Both NumPy arrays and Python lists are mutable, meaning you can modify their elements.

6.Dimensionality:

-    NumPy Arrays: Support multi-dimensional arrays (e.g., 2D, 3D arrays) which are useful for scientific computing.
    
-    Python Lists: Can also represent multi-dimensional data using nested lists, but it is less efficient and less intuitive.

7.Indexing and Slicing:

-    NumPy Arrays: Support more advanced and efficient indexing and slicing operations.
    
-    Python Lists: Support basic slicing and indexing.

8.Element-wise Operations:

-    NumPy Arrays: Allow element-wise operations directly (e.g., addition, subtraction).
    
-    Python Lists: Require manual iteration to perform element-wise operations.

#### 4.Create two 1-D arrays with numbers and strings respectively.

In [3]:
import numpy as np

In [67]:
#creatinf 1D number and string arrays
number_array=np.array([1,2,3,4],dtype="i")
string_array=np.array(["Ram","Sita","lakshman"])

print("Number array is:",number_array)
print("String array is:",string_array)

Number array is: [1 2 3 4]
String array is: ['Ram' 'Sita' 'lakshman']


#### 5.Create 2-D and 3-D arrays. And check their shape and dimensions using (shape and ndim methods).


In [76]:
#creating 2-D and 3-D arrays
two_D_array=np.array([[1,2],[3,4]])
three_D_array=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[5,4,3]]])

#checking shape and dimension 
print("Shape of 2D array:",two_D_array.shape)
print("Shape of 3D array:",three_D_array.shape)
print("Dimension of 2D array:",two_D_array.ndim)
print("Dimension of 3D array:",three_D_array.ndim)

Shape of 2D array: (2, 2)
Shape of 3D array: (2, 2, 3)
Dimension of 2D array: 2
Dimension of 3D array: 3


#### 6.Create a 1D NumPy array with elements from 1 to 10 using arange().
#### Create a 2D array of size 3x3 filled with zeros using zeros().


In [102]:
#creating 1D array using arange()
x=np.arange(1,10)
print("1D array:",x)

#creating 2D array 3*3 with zeros
zero_matrix=np.zeros(shape=(3,3) ,dtype="i")
print(zero_matrix)

1D array: [1 2 3 4 5 6 7 8 9]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 7.Create an array [5, 10, 15, 20, 25]. Find its size, item size, and total bytes used by the array.
#### Use linspace() to generate an array of 7 equally spaced numbers between 0 and 14.


In [121]:
# size - is used to find the size of array
# itemsize - is used to find each item size in an array
# nbytes - is used to find the array occupied bytes will display

numbers=np.array([5,10,15,20,15])
print("Size:",numbers.size)
print("iem size:",numbers.itemsize)
print("total number of bytes used:",numbers.nbytes)


# linespace()  - is used to generate an array of evenly spaced numbers
# np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axis=0)

x=np.linspace(0,14,num=7)
print(x)

Size: 5
iem size: 4
total number of bytes used: 20
[ 0.          2.33333333  4.66666667  7.          9.33333333 11.66666667
 14.        ]


#### 8.Create a 4x4 identity matrix using eye().
#### Create a 3x3 diagonal matrix with the diagonal values [1, 2, 3] using diag().
#### Create a 2x3 array filled with the value 9 using full().


In [135]:
# eye() - is used to create indentity matrix
identitiy=np.eye(4,dtype="i")
print(identitiy)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [143]:
# diag() - is used to create diagonal matrix
x=[1,2,3]
diagonal=np.diag(x)
print(diagonal)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [147]:
#full()
print(np.full((2,3),9,dtype="i"))

[[9 9 9]
 [9 9 9]]


#### 9.Generate a 3x3 array of random numbers between 0 and 1 using random.rand().
#### Create a 4x4 array of random integers between 10 and 50 using random.randint().
#### Generate a 1D array of 5 random numbers from a normal distribution using random.randn().
#### Generate a 2D array of shape (2, 4) with random values uniformly distributed between -5 and 5 using random.uniform().


In [52]:
# to print random numbers between   0 and 1    use   -             rand(dinension1,dimension2,....) 
print(f"Random numbers between 0 and 1 is:\n{np.random.rand(3,3)}\n")


#to print random integres use   -                                  randint(low,high=None,size=None dtype=int)
print(f"Random integers between 10 and 50:\n{np.random.randint(10,51,size=(4,4))}\n")

#to generate random numbers from normal distribution  we use    -  randn(dimension1,dimension2,.....)
print(f"random numbers from normal distribution:\n{np.random.randn(5)}\n")

#to generate uniform random values                              -    uniform(low=0,high=1.0,size=None)
print(f"uniform random numbers:\n{np.random.uniform(-5,5,size=(2,4))}")

Random numbers between 0 and 1 is:
[[0.85410476 0.37973148 0.53081372]
 [0.1867257  0.97626859 0.31506132]
 [0.71114298 0.3517593  0.40217339]]

Random integers between 10 and 50:
[[38 11 50 34]
 [39 47 38 39]
 [30 34 20 12]
 [10 50 17 23]]

random numbers from normal distribution:
[-0.62222623 -1.44502787 -1.52244184  1.59969973 -0.13728935]

uniform random numbers:
[[-4.42785918  2.52730029  0.71322529  0.08626968]
 [ 0.19025886 -0.89542884  0.54616591 -2.0888092 ]]


#### 11.Create a 1D array [10, 20, 30, 40, 50]. Access the third element and update it to 35.
#### Create a 2D array of shape (3, 4) with values from 1 to 12. Slice and extract the second row.
#### From the same array, extract all elements in the last column.


In [2]:
#creating 1D array
import numpy as np
numbers=np.array([10,20,30,40,50])
#updating third element
numbers[2]=35
print(numbers)

[10 20 35 40 50]


In [4]:
#creating 2D array
rangevalues=np.arange(1,13).reshape(3,4)
print(rangevalues)
print("Extracting second row using slicing:",rangevalues[1,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Extracting second row using slicing: [5 6 7 8]


In [10]:
print("all elements from the last column:",rangevalues[:,-1])
print(rangevalues[:,-1])

all elements from the last column: [ 4  8 12]
[ 4  8 12]


#### 11.Create a 3x3 array of ones using ones() and change its dtype to int.
#### Create an array [1, 2, 3, 4, 5] and multiply each element by 2.


In [104]:
#creating ones array   - ones((dimension),dtype=None)
arr=np.ones((3,3),dtype="i")
print(arr)


arr1=np.array([1,2,3,4,5])
print("Multiply each element by 2:",arr1*2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
Multiply each element by 2: [ 2  4  6  8 10]


#### 12.Create a 1D NumPy array with values from 1 to 10. Access the elements at indices 2, 5, and 7
#### Given an array `arr = np.array([10, 20, 30, 40, 50, 60, 70])`, extract a slice that contains the elements from index **2 to 5**.
#### Create an array of 10 random integers between 1 and 20. Extract all elements greater than 10.


In [117]:
numbers=np.arange(1,11)
print(numbers)
print("Accessing 2,5,7 elements:",numbers[[2,5,7]])

[ 1  2  3  4  5  6  7  8  9 10]
Accessing 2,5,7 elements: [3 6 8]


In [119]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print("elements from index 2 to 5:",arr[2:6])

elements from index 2 to 5: [30 40 50 60]


In [131]:
randomnumbers=np.random.randint(1,21, size=10)
print(randomnumbers)

print("Random numbers >10 are:",randomnumbers[randomnumbers>10])

[13 13  9 13 13 10 17 12  2  2]
Random numbers >10 are: [13 13 13 13 17 12]


#### 13.Create a NumPy array of size 6.  
#### Replace the second element with 99.
#### Update a slice of elements from index 2 to 4 with 0.  
#### Set the last three elements to 10.  


In [150]:
arr=np.arange(6)
print(arr)
arr[1]=99
print("replace of second element by 99:",arr)
arr[2:5]=0
print("elements from index 2 to 4 with 0:",arr)
arr[-3:]=10
print("set last three element s to 10:",arr)



[0 1 2 3 4 5]
replace of second element by 99: [ 0 99  2  3  4  5]
elements from index 2 to 4 with 0: [ 0 99  0  0  0  5]
set last three element s to 10: [ 0 99  0 10 10 10]


#### 14.Updating a 2D Array  
#### Create a 3x3 NumPy array with values from 1 to 9  .
#### Replace the second row with all 5s.  
#### Update the third column with values [8, 9, 10.


In [163]:
arr=np.arange(1,10).reshape(3,3)
print(arr)
arr[1,:]=5
print("Replacing second row to 5's:\n",arr)
arr[:,-1]=[8,9,10]
print("Upadating third column values to [8,9,10]:\n",arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Replacing second row to 5's:
 [[1 2 3]
 [5 5 5]
 [7 8 9]]
Upadating third column values to [8,9,10]:
 [[ 1  2  8]
 [ 5  5  9]
 [ 7  8 10]]


#### 15.Using a Condition to Modify Elements:  
#### Create a NumPy array with random numbers from 1 to 20.  
#### Set all values greater than 10 to zero.  


In [179]:
arr=np.random.randint(1,21,size=20)
print("random numbers from 1 to 20:",arr)
print("random umbers set to gretaer than 10:",arr[arr>10])

random numbers from 1 to 20: [14 14 12  6 18 17 19 18 13  1 17  3  9  6 18  8  8  8  5 17]
random umbers set to gretaer than 10: [14 14 12 18 17 19 18 13 17 18 17]


#### 16.Create an array [10, 20, 30, 40] and insert 25 at index 2.  

In [184]:
arr=np.array([10,20,30,40])
arr[2]=25
print("array after modification:",arr)

array after modification: [10 20 25 40]


#### 17.Create an array [1, 2, 3] and append [4, 5, 6] to it. 

In [187]:
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
result=np.append(arr,arr1)
print("after appending:",result)

after appending: [1 2 3 4 5 6]


#### 18.Create an array [5, 10, 15, 20, 25] and delete the third element. 

In [190]:
arr=np.array([5,10,15,20,25])
result=np.delete(arr,2)
print("after deletion of third element:",result)

after deletion of third element: [ 5 10 20 25]


#### 19.Create an array from 1 to 12 and reshape it into a 3×4 matrix. 

In [199]:
arr=np.arange(1,13)
print(arr)
arr=arr.reshape(3,4)
print("after reshape the array is:\n",arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
after reshape the array is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### 20.Create a 3×3 matrix and find its transpose using np.transpose().

In [206]:
arr=np.arange(9).reshape(3,3)
print(arr)
arr=arr.transpose()
print("after transpose:\n",arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
after transpose:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]


#### 21.Create two arrays:  
#### A = np.array([2, 4, 6]), B = np.array([1, 2, 3]).  
#### Perform element-wise addition, subtraction, multiplication, and division.  


In [209]:
A = np.array([2, 4, 6])
B = np.array([1, 2, 3])
print("Addition:\n",A+B)
print("Substraction:\n",A-B)
print("Multiplication:\n",A*B)
print("Division:\n",A/B)

Addition:
 [3 6 9]
Substraction:
 [1 2 3]
Multiplication:
 [ 2  8 18]
Division:
 [2. 2. 2.]


#### 22.Create an array with values [4, 8, 15, 16, 23, 42].  
#### Compute sum, min, max, mean, median, variance, standard deviation, and correlation coefficient.  


In [214]:
import numpy as np

# Create the array
array = np.array([4, 8, 15, 16, 23, 42])

# Compute statistics
sum_value = np.sum(array)
min_value = np.min(array)
max_value = np.max(array)
mean_value = np.mean(array)
median_value = np.median(array)
variance_value = np.var(array)
std_deviation_value = np.std(array)
correlation_coefficient = np.corrcoef(array)

print("Array:", array)
print("Sum:", sum_value)
print("Min:", min_value)
print("Max:", max_value)
print("Mean:", mean_value)
print("Median:", median_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation_value)
print("Correlation Coefficient:", correlation_coefficient)


Array: [ 4  8 15 16 23 42]
Sum: 108
Min: 4
Max: 42
Mean: 18.0
Median: 15.5
Variance: 151.66666666666666
Standard Deviation: 12.315302134607444
Correlation Coefficient: 1.0


In [49]:
import sys
import numpy as np

#creating list of 10000 integers
list1=list(range(100000))

#creating array of 10000 integers
arr1=np.arange(100000)

#print size of list and array
print(f"Size of list is:{sys.getsizeof(list1)} bytes")
print(f"Size of array is: {arr1.nbytes} bytes")

#import time module
import time

#sum the list
start_time=time.time()
sum_list=sum(list1)
end_time=time.time()
list_sum_time=(start_time-end_time)*1000

#sum the array
start_time=time.time()
sum_arr=np.sum(arr1)
end_time=time.time()
arr_sum_time=(start_time-end_time)*1000

print("list sum:",sum_list)
print("arry sum:",sum_arr)

#time taken to sum array and list
print(f"time taken to sum list:{list_sum_time:.2f} milliseconds")
print(f"time taken to sum arr:{arr_sum_time:.2f} milliseconds")

Size of list is:800056 bytes
Size of array is: 400000 bytes
list sum: 4999950000
arry sum: 704982704
time taken to sum list:-6.61 milliseconds
time taken to sum arr:0.00 milliseconds
